// Generated by `npm run generate:components` from zbk-radio.manifest.json.
// Do not edit by hand — edit the manifest and regenerate.
import type { SlotContract } from "../base/slot-contract";

export const slotContract: SlotContract = {
  slots: ["default", "checked", "unchecked"],
  required: ["default"],
};
