// Hero "Reskin" presets. The token-diff data is GENERATED by the hero-theme build
// (`npm run build:hero-themes` → `generated/hero-themes.json`) from the same
// `theme/zebkit-hero-*` override sets the scoped CSS is compiled from, so the panel
// can never drift from what actually re-skins. This module only adds presentation
// metadata (labels, ordering) and derives a small set of headline diff rows.
import rawDiffs from './generated/hero-themes.json';

export type HeroThemeName = 'swiss' | 'brutalist' | 'terminal' | 'editorial';

export interface HeroTheme {
  name: HeroThemeName;
  label: string;
  blurb: string;
}

/** Order = the switcher chip order. Swiss is the clean baseline. */
export const heroThemes: HeroTheme[] = [
  { name: 'swiss', label: 'Swiss', blurb: 'International typographic — grotesque, red, hairline grid.' },
  { name: 'brutalist', label: 'Brutalist', blurb: 'Raw concrete — black ink, acid yellow, zero radius.' },
  { name: 'terminal', label: 'Terminal', blurb: 'Phosphor CRT — dark canvas, green-on-black mono.' },
  { name: 'editorial', label: 'Editorial', blurb: 'Literary print — warm paper, wine accent, serif display.' }
];

const diffs = rawDiffs as Record<HeroThemeName, Record<string, string>>;

export interface DiffRow {
  label: string;
  /** The themed value, prettified (primitive ramp step or font family). */
  value: string;
}

/** Strip a trailing ramp step (`red-600` → `red`) for family-level display. */
function family(value: string | undefined): string {
  if (!value) return '—';
  return value.replace(/-\d+$/, '');
}

function fontName(value: string | undefined): string {
  if (!value) return '—';
  return value.replace(/["']/g, '').split(',')[0].trim();
}

/**
 * Headline diff rows for the panel: the most legible changes, derived from the
 * generated map. Caption stays honest — `totalChanged` is the real count.
 */
export function diffFor(name: HeroThemeName): { rows: DiffRow[]; totalChanged: number } {
  const d = diffs[name] ?? {};
  const rows: DiffRow[] = [
    { label: 'Canvas', value: d['app-canvas'] ?? '—' },
    { label: 'Ink', value: d['app-ink'] ?? '—' },
    { label: 'Primary accent', value: family(d['accent-primary-600']) },
    { label: 'Secondary accent', value: family(d['accent-secondary-600']) },
    { label: 'Display type', value: fontName(d['font-family-alt']) },
    { label: 'Body type', value: fontName(d['font-family-primary']) },
    { label: 'Radius (md)', value: d['border-radius-md'] ?? '—' }
  ];
  return { rows, totalChanged: Object.keys(d).length };
}
