// Hero "Reskin" presets. The token-diff data is GENERATED by the hero-theme build
// (`npm run build:hero-themes` → `generated/hero-themes.json`) from the same
// `theme/zebkit-hero-*` override sets the scoped CSS is compiled from, so the panel
// can never drift from what actually re-skins. This module only adds presentation
// metadata (labels, ordering) and derives a small set of headline diff rows.
import rawDiffs from './generated/hero-themes.json';

export type HeroThemeName = 'apple' | 'material' | 'atlassian' | 'carbon' | 'uber' | 'fluent';

export interface HeroTheme {
  name: HeroThemeName;
  label: string;
  blurb: string;
  /** Proper name of the real design system this preset nods to. */
  source: string;
  /** The real design system's homepage — opened from the hero header. */
  href: string;
}

/**
 * Each preset reskins the same markup to evoke a well-known design system.
 * `name` = the theme key / `data-zbk-theme` value; `label` is the cheeky chip
 * caption; `source`/`href` point at the real system. Order = the switcher chip
 * order; Apple is the clean baseline.
 */
export const heroThemes: HeroTheme[] = [
  { name: 'apple', label: "Cupertino'd", blurb: 'Calm minimalism — off-white canvas, SF system type, system blue.', source: 'Apple', href: 'https://developer.apple.com/design/human-interface-guidelines/' },
  { name: 'material', label: 'Materialist', blurb: 'Material You — lilac primary, soft rounded shapes, pill buttons, Roboto.', source: 'Material', href: 'https://m3.material.io/' },
  { name: 'atlassian', label: 'Confluenced', blurb: 'Workspace blue — Atlassian blue, Inter UI, crisp 4px corners.', source: 'Atlassian', href: 'https://atlassian.design/' },
  { name: 'carbon', label: 'Carbon copy', blurb: 'Industrial grid — IBM Plex, electric blue, razor-sharp corners.', source: 'Carbon', href: 'https://carbondesignsystem.com/' },
  { name: 'uber', label: 'Uberesque', blurb: 'Monochrome motion — black buttons, Base Blue accent, Manrope display.', source: 'Base', href: 'https://base.uber.com/' },
  { name: 'fluent', label: 'Redmond\'d', blurb: 'Acrylic calm — Fluent 2 brand blue, Segoe-style sans, soft 4px corners.', source: 'Fluent', href: 'https://fluent2.microsoft.design/' }
];

const diffs = rawDiffs as Record<HeroThemeName, Record<string, string>>;

export interface DiffRow {
  label: string;
  /** The themed value, prettified (primitive ramp step or font family). */
  value: string;
}

/** Strip a trailing ramp step (`red-600` → `red`) for family-level display. */
function family(value: string | undefined): string {
  if (!value) return '—';
  return value.replace(/-\d+$/, '');
}

function fontName(value: string | undefined): string {
  if (!value) return '—';
  return value.replace(/["']/g, '').split(',')[0].trim();
}

/**
 * Headline diff rows for the panel: the most legible changes, derived from the
 * generated map. Caption stays honest — `totalChanged` is the real count.
 */
export function diffFor(name: HeroThemeName): { rows: DiffRow[]; totalChanged: number } {
  const d = diffs[name] ?? {};
  const rows: DiffRow[] = [
    { label: 'Canvas', value: d['app-canvas'] ?? '—' },
    { label: 'Ink', value: d['app-ink'] ?? '—' },
    { label: 'Primary accent', value: family(d['accent-primary-600']) },
    { label: 'Secondary accent', value: family(d['accent-secondary-600']) },
    { label: 'Display type', value: fontName(d['font-family-alt']) },
    { label: 'Body type', value: fontName(d['font-family-primary']) },
    { label: 'Monospaced type', value: fontName(d['font-family-monospace']) },
    { label: 'Radius (md)', value: d['border-radius-md'] ?? '—' }
  ];
  return { rows, totalChanged: Object.keys(d).length };
}
