import type { CompiledToken } from '../data/compiled-tokens';

export interface TokenRow {
  token: string;
  type: string;
  value: string | number;
  description: string;
  cssProperties: string[];
}

export type { CompiledToken };
export type CompiledTokenMap = Record<string, CompiledToken>;

/**
 * Docs projections carry the canonical display value generated by the source
 * token registry. The fallback keeps hand-built fixtures readable without
 * reimplementing structured DTCG serialization in the decoupled docs app.
 */
export function formatTokenValue(
  value: CompiledToken['$value'],
  displayValue?: string
): string | number {
  if (displayValue != null) return displayValue;
  if (typeof value === 'string' || typeof value === 'number') return value;
  if (typeof value === 'boolean') return String(value);
  return value == null ? '' : JSON.stringify(value);
}

export function buildTokenRows(
  tokenKey: string,
  tokens: CompiledTokenMap | undefined
): TokenRow[] {
  if (!tokens) return [];

  return Object.entries(tokens)
    // The group-level $extensions member is scale metadata, not a token.
    .filter(([name]) => !name.startsWith('$'))
    .map(([name, token]) => ({
      token: `${tokenKey}.${name}`,
      type: token.$type,
      value:
        token.$value != null
          ? formatTokenValue(token.$value, token.$displayValue)
          : token.$extensions?.['dev.zebkit']?.scale?.index ?? '',
      description: token.$description,
      cssProperties: token.$cssProperties ?? [],
    }));
}
