// Custom Elements Manifest: the machine-readable component contract
// (GRAMMAR.md §10). Generated by `npm run build:cem`; CI treats drift between
// this config's inputs and the committed manifest as a failure.
export default {
  globs: ['src/components/**/index.ts', 'src/components/base/*.ts'],
  exclude: ['src/components/**/*.test.ts', 'src/components/**/variants/**'],
  outdir: '.',
  litelement: true,
};
