import { z } from "zod";
import { tokenObjectSchema } from "@definitions/tokens";

export const tokenSchema = z.object({
  "viewport-modifier": tokenObjectSchema,
  "max-size-modifer": tokenObjectSchema,
  "neg-15": tokenObjectSchema,
  "neg-10": tokenObjectSchema,
  "neg-9": tokenObjectSchema,
  "neg-8": tokenObjectSchema,
  "neg-7": tokenObjectSchema,
  "neg-6": tokenObjectSchema,
  "neg-5": tokenObjectSchema,
  "neg-4": tokenObjectSchema,
  "neg-3": tokenObjectSchema,
  "neg-205": tokenObjectSchema,
  "neg-2": tokenObjectSchema,
  "neg-105": tokenObjectSchema,
  "neg-1": tokenObjectSchema,
  "neg-05": tokenObjectSchema,
  "neg-025": tokenObjectSchema,
  "neg-2px": tokenObjectSchema,
  "neg-1px": tokenObjectSchema,
  "0": tokenObjectSchema,
  "1px": tokenObjectSchema,
  "2px": tokenObjectSchema,
  "025": tokenObjectSchema,
  "05": tokenObjectSchema,
  "1": tokenObjectSchema,
  "105": tokenObjectSchema,
  "2": tokenObjectSchema,
  "205": tokenObjectSchema,
  "3": tokenObjectSchema,
  "4": tokenObjectSchema,
  "5": tokenObjectSchema,
  "6": tokenObjectSchema,
  "7": tokenObjectSchema,
  "8": tokenObjectSchema,
  "9": tokenObjectSchema,
  "10": tokenObjectSchema,
  "15": tokenObjectSchema,
  "20": tokenObjectSchema,
  "25": tokenObjectSchema,
  "30": tokenObjectSchema,
  "40": tokenObjectSchema,
  "50": tokenObjectSchema,
  "60": tokenObjectSchema,
  "70": tokenObjectSchema,
  "80": tokenObjectSchema,
  "90": tokenObjectSchema,
  "100": tokenObjectSchema,
});
