export const zbkRadioTokenKeys = {
  "zbk-radio": {
    rootAllowedKeys: ["styles"],
    styles: {
      allowed: [
        "radio-size",
        "radio-border-radius",
        "radio-border-width",
        "radio-background",
        "radio-background-checked",
        "radio-border-color",
        "radio-border-color-hover",
        "radio-border-color-active",
        "radio-border-color-disabled",
        "radio-indicator-size",
        "radio-indicator-border-radius",
        "radio-indicator-color",
        "radio-indicator-disabled-color",
        "radio-focus-ring-color",
        "radio-focus-ring-width",
        "radio-focus-ring-offset",
        "radio-transition-timing-function",
        "radio-transition-duration",
        "radio-disabled-opacity",
        "radio-label-color",
        "radio-label-disabled-color",
        "radio-label-font-family",
        "radio-label-font-size",
        "radio-label-font-weight",
        "radio-label-line-height",
        "radio-label-letter-spacing",
        "radio-label-gap",
      ],
      subsets: {
        "radio-size": { type: "spacing" },
        "radio-border-radius": { type: "borderRadius" },
        "radio-border-width": { type: "borderWidth" },
        "radio-background": { type: "color" },
        "radio-background-checked": { type: "color" },
        "radio-border-color": { type: "color" },
        "radio-border-color-hover": { type: "color" },
        "radio-border-color-active": { type: "color" },
        "radio-border-color-disabled": { type: "color" },
        "radio-indicator-size": { type: "spacing" },
        "radio-indicator-border-radius": { type: "borderRadius" },
        "radio-indicator-color": { type: "color" },
        "radio-indicator-disabled-color": { type: "color" },
        "radio-focus-ring-color": { type: "color" },
        "radio-focus-ring-width": { type: "borderWidth" },
        "radio-focus-ring-offset": { type: "spacing" },
        "radio-transition-timing-function": { type: "custom" },
        "radio-transition-duration": { type: "custom" },
        "radio-disabled-opacity": { type: "custom" },
        "radio-label-color": { type: "color" },
        "radio-label-disabled-color": { type: "color" },
        "radio-label-font-family": { type: "fontFamily" },
        "radio-label-font-size": { type: "fontSize" },
        "radio-label-font-weight": { type: "custom" },
        "radio-label-line-height": { type: "lineHeight" },
        "radio-label-letter-spacing": { type: "letterSpacing" },
        "radio-label-gap": { type: "spacing" },
      },
    },
  },
};
