#!/usr/bin/env tsx
// Generates the primitive palette SCSS from the palette token definition
// (DTCG alignment decision D7 — the palette's source of truth is token space).
// Emits the primitiveColor mixin (shared lightness ramp), one partial per
// family (hue/saturation), and palette/styles.scss (family @use list + global
// colors). Every file is overwritten wholesale — edit
// src/tokens/colors/palette/tokens/palette-definition.ts and regenerate.
//
// Run: npm run generate:palette (--check diffs without writing)

import fs from "fs-extra";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  PALETTE_FAMILIES,
  PALETTE_GLOBALS,
  PALETTE_RAMP,
  type PaletteFamilyDefinition,
} from "../../tokens/colors/palette/tokens/palette-definition";

const __filename = fileURLToPath(import.meta.url);
const rootDir = path.resolve(path.dirname(__filename), "../../..");

const MIXIN_PATH = "src/tokens/styles/mixins/_primitive-color.scss";
const PALETTE_DIR = "src/tokens/colors/palette";

const GENERATED_HEADER =
  "// GENERATED by generate:palette from src/tokens/colors/palette/tokens/palette-definition.ts — do not edit; edit the definition and regenerate.";

function renderMixin(): string {
  const rampLines = PALETTE_RAMP.map(
    ({ step, lightness }) =>
      `  --#{prefix.$cssVar}-color-#{$name}-${step}: hsl(var(--#{prefix.$cssVar}-color-#{$name}-hue), var(--#{prefix.$cssVar}-color-#{$name}-saturation), ${lightness}%);`
  ).join("\n");

  return `${GENERATED_HEADER}
// Emits --zbk-color-{name}-{step} CSS custom properties for a primitive color family.
// Usage: @include primitiveColor(red, 0, 80%);
@use 'tokens/styles/variables/prefix' as prefix;

@mixin primitiveColor($name, $hue, $saturation) {
  --#{prefix.$cssVar}-color-#{$name}-hue: #{$hue};
  --#{prefix.$cssVar}-color-#{$name}-saturation: #{$saturation};
${rampLines}
}
`;
}

function renderFamily(family: PaletteFamilyDefinition): string {
  return `${GENERATED_HEADER}
@use 'tokens/styles/mixins/primitive-color' as color-utils;
:root {
  @include color-utils.primitiveColor("${family.name}", ${family.hue}, ${family.saturation}%);
}
`;
}

function renderStyles(): string {
  const uses = [...PALETTE_FAMILIES]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((family) => `@use './${family.name}';`)
    .join("\n");
  const globals = PALETTE_GLOBALS.map(
    (global) => `  --zbk-color-${global.name}: ${global.value};`
  ).join("\n");

  return `${GENERATED_HEADER}
${uses}

:root {
${globals}
}
`;
}

async function main() {
  const outputs = new Map<string, string>();
  outputs.set(MIXIN_PATH, renderMixin());
  for (const family of PALETTE_FAMILIES) {
    outputs.set(`${PALETTE_DIR}/_${family.name}.scss`, renderFamily(family));
  }
  outputs.set(`${PALETTE_DIR}/styles.scss`, renderStyles());

  // --check renders in-memory and diffs against the committed files without
  // writing — the "generated palette SCSS is up to date" guard for `check`/CI.
  const checkOnly = process.argv.includes("--check");
  const drifted: string[] = [];

  for (const [relPath, output] of outputs) {
    const outputPath = path.resolve(rootDir, relPath);
    if (checkOnly) {
      const current = (await fs.pathExists(outputPath))
        ? await fs.readFile(outputPath, "utf8")
        : null;
      if (current !== output) drifted.push(relPath);
      continue;
    }
    await fs.ensureDir(path.dirname(outputPath));
    await fs.writeFile(outputPath, output, "utf8");
    console.log(`generated ${relPath}`);
  }

  if (checkOnly) {
    if (drifted.length > 0) {
      console.error(
        `Palette SCSS is out of date with the palette definition:\n${drifted
          .map((s) => `  - ${s}`)
          .join("\n")}\nRun 'npm run generate:palette' and commit the result (do not hand-edit generated palette SCSS).`
      );
      process.exitCode = 1;
    } else {
      console.log(`Palette SCSS is up to date (${outputs.size} file(s)).`);
    }
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.stack ?? error.message : String(error));
  process.exitCode = 1;
});
