// Renders a component manifest's slot contract as the generated
// src/components/{name}/slot-contract.ts module. Shared by generate.ts (which
// writes the file) and lint.ts (rule C6, which diffs the file against what
// this would emit — so manifest and runtime can never drift).

export function renderSlotContract(manifest: {
  tag: string;
  slots: Record<string, { required?: boolean }>;
}): string {
  const slots = Object.keys(manifest.slots);
  const required = slots.filter((name) => manifest.slots[name].required);
  const list = (names: string[]) => names.map((name) => JSON.stringify(name)).join(", ");

  return `// Generated by \`npm run generate:components\` from ${manifest.tag}.manifest.json.
// Do not edit by hand — edit the manifest and regenerate.
import type { SlotContract } from "../base/slot-contract";

export const slotContract: SlotContract = {
  slots: [${list(slots)}],
  required: [${list(required)}],
};
`;
}
